version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/d/db/mongo_data:/data/db"
      #- D:\db\mongo_data: /data/db
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"