apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    name: mongo-pod
    app: product-service-app
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: mongo-db-volume
  volumes:
    - name: mongo-db-volume
      hostPath:
        # directory location on host
        path: /d/db/mongo_data
        # this field is optional
        type: Directory