apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    name: redis-db-service
    app: product-service-app
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017
  selector:
    name: mongo-pod
    app: product-service-app